name: NodeJS CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: | 
        npm install
        npm run build

    - name: Put variables to github env
      run: |
        echo VERSION_NAME=$(node -e 'console.log(require("./package.json").version)') >> $GITHUB_ENV
        echo APP_NAME=$(node -e 'console.log(require("./package.json").name)') >> $GITHUB_ENV

    - name: Fail if version is empty
      if: ${{ env.VERSION_NAME == '' }}
      run: exit 1

    - name: Fail if app name is empty
      if: ${{ env.APP_NAME == '' }}
      run: exit 1

    - name: Create Release
      run: | 
        cp dist/bundle.js ${{ env.APP_NAME }}-${{ env.VERSION_NAME }}.js
        gh release create v${{ env.VERSION_NAME }} ${{ env.APP_NAME }}-${{ env.VERSION_NAME }}.js
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
